@rootURL = http://localhost:5089

GET {{rootURL}}/api/Message/
Accept: application/json

###
GET {{rootURL}}/api/Message/text
Accept: application/json

###
POST https://randomnessnessapi-production.up.railway.app/api/message
Content-Type: application/json

{
  "text" : "THIS IS SO PEAK CINEMA"
}